import * as dotenv from "dotenv"; dotenv.config({ path: ".env.local" });
import * as fs from "fs";

async function main() {
  // 0. Load folderKey→email map generated by last probe (106 keys)
  const parseCsv = (ln: string): string[] => {
    const out: string[] = []; let cur = ""; let inQ = false;
    for (let i = 0; i < ln.length; i++) {
      const c = ln[i];
      if (c === '"') { inQ = !inQ; continue; }
      if (c === "," && !inQ) { out.push(cur); cur = ""; continue; }
      cur += c;
    }
    out.push(cur); return out;
  };
  const folderKeys = new Set<string>();
  for (const l of fs.readFileSync("/tmp/firebase-storage-listing.csv","utf8").split("\n").slice(1).filter(Boolean)) {
    const cols = parseCsv(l); const f = cols[0];
    if (!f.startsWith("members/")) continue;
    const parts = f.split("/"); if (parts.length >= 2 && parts[1] && parts[1] !== "members") folderKeys.add(parts[1]);
  }
  const realFk = [...folderKeys].filter(k => k.length >= 20);

  // Postgres
  const { Pool } = require("pg");
  const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
  const { rows: allPG } = await pool.query(`
    SELECT clerk_id, email_lower, visibility, is_active,
      COALESCE(data->>'tier', data->'subscription'->>'tier', data->'stripe'->>'tier', '') AS tier,
      data->>'avatarUrl' AS av, data->>'profileImage' AS pi, data->>'image' AS im,
      COALESCE(data->'stripe'->>'subscriptionId', data->'subscription'->>'id', '') AS stripe_sub_id
    FROM member_profiles
  `);
  const pgAllMap = new Map<string, typeof allPG[number]>();
  for (const r of allPG) pgAllMap.set(r.email_lower, r);

  // 1. Regenerate the orphanToEmail map (no need to re-run firestore scan — load the 106 emails by re-importing the probe's logic)
  const mod = require("firebase-admin");
  let pk = process.env.FIREBASE_PRIVATE_KEY || "";
  pk = pk.trim();
  if (pk.startsWith('"')) pk = pk.slice(1);
  if (pk.endsWith('"')) pk = pk.slice(0, -1);
  pk = pk.replace(/\\n/g, "\n");
  const certFn = mod.credential?.cert ?? mod.cert;
  const app = (mod.getApps().length) ? mod.getApp() : mod.initializeApp({
    credential: certFn({ projectId: process.env.FIREBASE_PROJECT_ID, clientEmail: process.env.FIREBASE_CLIENT_EMAIL, privateKey: pk }),
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  });
  const fM = require("firebase-admin/firestore");
  const firestore = fM.getFirestore(app);
  const folderKeyInPG = new Set<string>();
  for (const r of allPG) {
    for (const s of [r.av, r.pi, r.im]) {
      const m = (s || "").match(/\/uploads\/members\/([^/]+)\//);
      if (m) folderKeyInPG.add(m[1]);
    }
  }
  const orphans = realFk.filter(k => !folderKeyInPG.has(k));
  console.log("Total FB real folderKeys:", realFk.length, "in-PG:", folderKeyInPG.size, "orphans:", orphans.length);
  const orphanSet = new Set(orphans);

  const orphanToEmail: Record<string, Set<string>> = {};
  for (const cname of ["memberImageBackup","newMemberCollection","members_v2"]) {
    let cursor: any = null; let safe = 0;
    while (safe++ < 50) {
      let snap: any;
      try {
        const qBase: any = firestore.FieldPath
          ? firestore.collection(cname).orderBy(firestore.FieldPath.documentId()).limit(200)
          : firestore.collection(cname).limit(500);
        snap = cursor ? await qBase.startAfter(cursor).get() : await qBase.get();
      } catch { snap = await firestore.collection(cname).get(); }
      if (snap.empty) break;
      for (const doc of snap.docs) {
        const id = doc.id;
        const d = doc.data() || {};
        const email = (id.includes("@") ? id : (d.email || d.emailLower || "") as string).toString().toLowerCase();
        const strs: string[] = [];
        const walk = (o: any) => {
          if (!o) return;
          if (typeof o === "string") { strs.push(o); return; }
          if (Array.isArray(o)) { o.forEach(walk); return; }
          if (typeof o === "object") Object.values(o).forEach(walk);
        };
        walk(d);
        for (const s of strs) {
          for (const fk of orphans) {
            if (s.includes(`members/${fk}/`) || (s.length === fk.length && s === fk && s.length >= 20)) {
              (orphanToEmail[fk] = orphanToEmail[fk] || new Set()).add(email);
            }
          }
        }
        cursor = doc;
      }
      if (snap.size < 200) break;
    }
  }
  // Also the orphan=id-field on newMemberCollection (1 hit)
  for (const cname of ["newMemberCollection","members_v2","memberImageBackup"]) {
    let cursor: any = null; let safe = 0;
    while (safe++ < 50) {
      let snap: any;
      try {
        const qBase = firestore.FieldPath
          ? firestore.collection(cname).orderBy(firestore.FieldPath.documentId()).limit(200)
          : firestore.collection(cname).limit(500);
        snap = cursor ? await qBase.startAfter(cursor).get() : await qBase.get();
      } catch { snap = await firestore.collection(cname).get(); }
      if (snap.empty) break;
      for (const doc of snap.docs) {
        const id = doc.id;
        const d = doc.data() || {};
        const email = (id.includes("@") ? id : (d.email || d.emailLower || "") as string).toString().toLowerCase();
        const uids = new Set<string>();
        for (const k of ["uid","id","docId","legacyId","legacyUid","memberId","firestoreId","firebaseUid","firestoreDocId","authUid"]) {
          const v = (d as any)[k];
          if (typeof v === "string") uids.add(v);
        }
        for (const v of uids) if (orphanSet.has(v)) (orphanToEmail[v] = orphanToEmail[v] || new Set()).add(email);
        cursor = doc;
      }
      if (snap.size < 200) break;
    }
  }
  const totalFkMapped = Object.keys(orphanToEmail).length;
  console.log("\nFB orphans mapped via Firestore → email:", totalFkMapped, "of", orphans.length, "orphans (", Math.round(100*totalFkMapped/orphans.length), "%)");

  // Classify each mapped orphan FK by ALL-PG state (not only visible):
  const rows: any[] = [];
  for (const fk of Object.keys(orphanToEmail)) {
    const emails = [...orphanToEmail[fk]].filter(Boolean);
    for (const em of emails) {
      const pg = pgAllMap.get(em);
      const hasRealPhoto = pg && [pg.av, pg.pi, pg.im].some(s =>
        s?.startsWith("/uploads/") || s?.startsWith("http") && !s.includes("gravatar.com"));
      rows.push({
        folderKey: fk,
        email: em,
        pg_status: pg ? `${pg.visibility}/${pg.is_active ? "active" : "inactive"}/${pg.tier || "no-tier"}` : "NOT_IN_PG",
        pg_clerk_id: pg?.clerk_id || "",
        pg_has_real_photo: !!hasRealPhoto,
        recoverable: pg ? (pg.visibility === "visible" && pg.is_active && !hasRealPhoto) : false,
        stripe_sub_id: pg?.stripe_sub_id || "",
      });
    }
  }
  // De-dup by folderKey (first email wins), but for NOT_IN_PG rows we also want to include all emails maybe match Stripe B4 list
  const seen = new Set<string>();
  const deduped: any[] = [];
  for (const r of rows) {
    if (seen.has(r.folderKey + "|" + r.email)) continue;
    seen.add(r.folderKey + "|" + r.email);
    deduped.push(r);
  }
  console.log("\n=== ORPHAN FOLDERKEY CLASSIFICATION (per fk+email) ===");
  const byStatus: Record<string, number> = {};
  for (const r of deduped) byStatus[r.pg_status] = (byStatus[r.pg_status] || 0) + 1;
  console.table(byStatus);
  const NOT_IN_PG = deduped.filter(r => r.pg_status === "NOT_IN_PG");
  console.log("\n=== NOT_IN_PG folderKey emails (", NOT_IN_PG.length, "rows) — these are candidates for MEMBERSHIP MISSING rows (Stripe B4) ===");
  console.table(NOT_IN_PG.slice(0, 60));
  const recoverable = deduped.filter(r => r.recoverable);
  console.log("\n=== RECOVERABLE VISIBLE/ACTIVE/NO-REAL-PHOTO (backfill blank-only) rows (", recoverable.length, ") ===");
  console.table(recoverable.slice(0, 60));
  const inPGinactiveOrInvisible = deduped.filter(r => r.pg_status !== "NOT_IN_PG" && !r.recoverable);
  console.log("\n=== PG EXISTS BUT INVISIBLE / INACTIVE / ALREADY HAS PHOTO (skip) (", inPGinactiveOrInvisible.length, ") ===");
  console.table(inPGinactiveOrInvisible.slice(0, 30));

  // Write out all
  const outHeader = "folderKey,email,pg_status,pg_clerk_id,pg_has_real_photo,recoverable,stripe_sub_id\n";
  const outCsv = outHeader + deduped.map(r => [r.folderKey, r.email, r.pg_status.replace(/,/g, ";"), r.pg_clerk_id, r.pg_has_real_photo, r.recoverable, r.stripe_sub_id].join(",")).join("\n") + "\n";
  fs.writeFileSync("/tmp/fb-folderkey-allpg-classification.csv", outCsv);
  console.log("\nWrote /tmp/fb-folderkey-allpg-classification.csv rows =", deduped.length);
  await pool.end();
}
main().catch(e => { console.error("FAIL", e); process.exit(1); });
